Add sentence for doing your own research
ms1-learner/cpp-01-ja pull request #9
Opened 2024-03-15 04:23 UTC by abolinsky

[Reference to english file](https://github.com/ms1-learner/cpp-01-en/tree/main/03_organization_and_testing/02_challenge)

2024-03-15 04:24 UTC, abolinsky commented
https://woven-dojo.atlassian.net/browse/CLD-554?atlOrigin=eyJpIjoiMjY1ZjVjZjYzZGZlNDQ1NjllODYwZTYyN2M0Y2UwNWIiLCJwIjoiaiJ9

2024-03-19 07:20 UTC, dancer-yuma requested changes
@abolinsky 
It is not wrong, but I changed it to be more like a suggestion.

2024-03-19 07:20 UTC, dancer-yuma commented on 03_organization_and_testing/02_challenge/README.md
> +C++11以降では4番目のタイプの記憶域期間が追加されています。何という記憶域期間ですか。自分自身で調査する必要があります。この記憶域期間を持つ `int` 型の変数 `thread_data` を宣言し、値10で初期化するには、どのようにしますか。
```suggestion
C++11以降では4番目のタイプの記憶域期間が追加されています。何という記憶域期間ですか。自分で調べてみましょう。この記憶域期間を持つ `int` 型の変数 `thread_data` を宣言し、値10で初期化するには、どのようにしますか。
```

2024-03-19 07:28 UTC, abolinsky commented on 03_organization_and_testing/02_challenge/README.md
> +C++11以降では4番目のタイプの記憶域期間が追加されています。何という記憶域期間ですか。自分自身で調査する必要があります。この記憶域期間を持つ `int` 型の変数 `thread_data` を宣言し、値10で初期化するには、どのようにしますか。
@dancer-yuma accepted

2024-03-19 07:30 UTC, merged